/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/components/about.vue')['default']
    Airport: typeof import('./src/components/Airport.vue')['default']
    AirStrip: typeof import('./src/components/AirStrip.vue')['default']
    BackgroundCleaner: typeof import('./src/components/BackgroundCleaner.vue')['default']
    ConfigProvider: typeof import('./src/components/ConfigProvider.vue')['default']
    FireWorks: typeof import('./src/components/FireWorks.vue')['default']
    FloatingMenu: typeof import('./src/components/FloatingMenu.vue')['default']
    IconLogosMarkdown: typeof import('~icons/logos/markdown')['default']
    LinkListView: typeof import('./src/components/LinkListView.vue')['default']
    ListView: typeof import('./src/components/ListView.vue')['default']
    LunarCalendar: typeof import('./src/components/LunarCalendar.vue')['default']
    PoemPaper: typeof import('./src/components/PoemPaper.vue')['default']
    ShareLink: typeof import('./src/components/ShareLink.vue')['default']
    SkillRadar: typeof import('./src/components/SkillRadar.vue')['default']
    TagPanel: typeof import('./src/components/TagPanel.vue')['default']
    ThreePlane: typeof import('./src/components/ThreePlane.vue')['default']
    WavingBorder: typeof import('./src/components/WavingBorder.vue')['default']
  }
}
