/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/components/about.vue')['default']
    AnimatedGallery: typeof import('./src/components/AnimatedGallery.vue')['default']
    ArchiveList: typeof import('./src/components/ArchiveList.vue')['default']
    BackgroundCleaner: typeof import('./src/components/BackgroundCleaner.vue')['default']
    CardListView: typeof import('./src/components/CardListView.vue')['default']
    ConfigProvider: typeof import('./src/components/ConfigProvider.vue')['default']
    CursorShineCards: typeof import('./src/components/CursorShineCards.vue')['default']
    FloatingMenu: typeof import('./src/components/FloatingMenu.vue')['default']
    HoverableCard: typeof import('./src/components/HoverableCard.vue')['default']
    IconLogosMarkdown: typeof import('~icons/logos/markdown')['default']
    LinkListView: typeof import('./src/components/LinkListView.vue')['default']
    ListView: typeof import('./src/components/ListView.vue')['default']
    LunarCalendar: typeof import('./src/components/LunarCalendar.vue')['default']
    PoemPaper: typeof import('./src/components/PoemPaper.vue')['default']
    ShareLink: typeof import('./src/components/ShareLink.vue')['default']
    TagPanel: typeof import('./src/components/TagPanel.vue')['default']
    WavingBorder: typeof import('./src/components/WavingBorder.vue')['default']
  }
}
