/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./../src/components/about.vue')['default']
    ConfigProvider: typeof import('./../src/components/ConfigProvider.vue')['default']
    FloatingMenu: typeof import('./../src/components/FloatingMenu.vue')['default']
    LinkListView: typeof import('./../src/components/LinkListView.vue')['default']
    ListView: typeof import('./../src/components/ListView.vue')['default']
    LunarCalendar: typeof import('./../src/components/LunarCalendar.vue')['default']
    ShareLink: typeof import('./../src/components/ShareLink.vue')['default']
    WavingBorder: typeof import('./../src/components/WavingBorder.vue')['default']
  }
}
