/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./../src/components/about.vue')['default']
    AnimatedGallery: typeof import('./../src/components/AnimatedGallery.vue')['default']
    ArchiveList: typeof import('./../src/components/ArchiveList.vue')['default']
    BackgroundCleaner: typeof import('./../src/components/BackgroundCleaner.vue')['default']
    CardListView: typeof import('./../src/components/CardListView.vue')['default']
    ConfigProvider: typeof import('./../src/components/ConfigProvider.vue')['default']
    CursorShineCards: typeof import('./../src/components/CursorShineCards.vue')['default']
    FloatingMenu: typeof import('./../src/components/FloatingMenu.vue')['default']
    FlyingPlane: typeof import('./../src/components/FlyingPlane.vue')['default']
    HexagonHolder: typeof import('./../src/components/HexagonHolder.vue')['default']
    HoverableCard: typeof import('./../src/components/HoverableCard.vue')['default']
    IconLogosMarkdown: typeof import('~icons/logos/markdown')['default']
    LinkListView: typeof import('./../src/components/LinkListView.vue')['default']
    ListView: typeof import('./../src/components/ListView.vue')['default']
    LunarCalendar: typeof import('./../src/components/LunarCalendar.vue')['default']
    PoemPaper: typeof import('./../src/components/PoemPaper.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShareLink: typeof import('./../src/components/ShareLink.vue')['default']
    TagPanel: typeof import('./../src/components/TagPanel.vue')['default']
    WavingBorder: typeof import('./../src/components/WavingBorder.vue')['default']
  }
}

// For TSX support
declare global {
  const About: typeof import('./../src/components/about.vue')['default']
  const AnimatedGallery: typeof import('./../src/components/AnimatedGallery.vue')['default']
  const ArchiveList: typeof import('./../src/components/ArchiveList.vue')['default']
  const BackgroundCleaner: typeof import('./../src/components/BackgroundCleaner.vue')['default']
  const CardListView: typeof import('./../src/components/CardListView.vue')['default']
  const ConfigProvider: typeof import('./../src/components/ConfigProvider.vue')['default']
  const CursorShineCards: typeof import('./../src/components/CursorShineCards.vue')['default']
  const FloatingMenu: typeof import('./../src/components/FloatingMenu.vue')['default']
  const FlyingPlane: typeof import('./../src/components/FlyingPlane.vue')['default']
  const HexagonHolder: typeof import('./../src/components/HexagonHolder.vue')['default']
  const HoverableCard: typeof import('./../src/components/HoverableCard.vue')['default']
  const IconLogosMarkdown: typeof import('~icons/logos/markdown')['default']
  const LinkListView: typeof import('./../src/components/LinkListView.vue')['default']
  const ListView: typeof import('./../src/components/ListView.vue')['default']
  const LunarCalendar: typeof import('./../src/components/LunarCalendar.vue')['default']
  const PoemPaper: typeof import('./../src/components/PoemPaper.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const ShareLink: typeof import('./../src/components/ShareLink.vue')['default']
  const TagPanel: typeof import('./../src/components/TagPanel.vue')['default']
  const WavingBorder: typeof import('./../src/components/WavingBorder.vue')['default']
}