/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AnimationTitle: typeof import('./components/AnimationTitle.vue')['default']
    ArticleMetadata: typeof import('./components/ArticleMetadata.vue')['default']
    Badge: typeof import('./components/Badge.vue')['default']
    CodeGroup: typeof import('./components/CodeGroup.vue')['default']
    Comment: typeof import('./components/Comment.vue')['default']
    Contributors: typeof import('./components/Contributors.vue')['default']
    CopyRight: typeof import('./components/CopyRight.vue')['default']
    DocAfter: typeof import('./components/DocAfter.vue')['default']
    HeaderProfile: typeof import('./components/HeaderProfile.vue')['default']
    LottiePanel: typeof import('./components/LottiePanel.vue')['default']
    NotFound: typeof import('./components/NotFound.vue')['default']
    OnBoard: typeof import('./components/OnBoard.vue')['default']
    PlaceHolder: typeof import('./components/PlaceHolder.vue')['default']
    Recommend: typeof import('./components/Recommend.vue')['default']
    Sponsor: typeof import('./components/Sponsor.vue')['default']
  }
}
